In [1]:
### Importing necessary libraries

import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
### Reading the churn modelling dataset
df = pd.read_csv('Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
X = df.iloc[:, 3:-1].values
y = df.iloc[:,-1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding the categorical variables

In [6]:
### Label encoding the gender column as it has only two values: Male and Female
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [8]:
### One Hot Encoding the geography column as it has 3 levels (More than binary as in Gender)
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Train Test Split

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=0)

### Feature Scaling


In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Building an Artificial Neural Network

In [12]:
### Initializing the ANN
ann = tf.keras.models.Sequential()

In [13]:
### Adding the input and hidden layer
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [14]:
### Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [15]:
### Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation = 'sigmoid'))

### Training the Artificial Neural Network

In [16]:
### Compiling the ann
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = 'accuracy')

In [17]:
### training the ann on training set
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5155 - accuracy: 0.7962
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4632 - accuracy: 0.7962
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4444 - accuracy: 0.7962
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4332 - accuracy: 0.7962
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4257 - accuracy: 0.7962
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4184 - accuracy: 0.7962
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4115 - accuracy: 0.8085
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4045 - accuracy: 0.8185
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3973 - accuracy: 0.8234
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3915 - accura

250/250 [==============================] - 1s 2ms/step - loss: 0.3288 - accuracy: 0.8646
Epoch 80/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3278 - accuracy: 0.8646
Epoch 81/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3286 - accuracy: 0.8666
Epoch 82/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3283 - accuracy: 0.8652
Epoch 83/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3281 - accuracy: 0.8658
Epoch 84/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3280 - accuracy: 0.8660
Epoch 85/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3279 - accuracy: 0.8659
Epoch 86/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3270 - accuracy: 0.8662
Epoch 87/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3279 - accuracy: 0.8645
Epoch 88/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3268 - accuracy: 

### Evaluating the test set

In [18]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test), 1)),1))

[[0 1]
 [0 0]
 [0 0]
 ...
 [0 0]
 [1 1]
 [0 0]]


### Making the confusion Matrix

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print()
print("The accuracy Score of the model is", accuracy_score(y_test, y_pred))

[[1523   70]
 [ 223  184]]

The accuracy Score of the model is 0.8535
