### Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

### Reading the dataset

In [2]:
df = pd.read_excel("Folds5x2_pp.xlsx")
df.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

### Separating the X (dependent variable) and y(independent variables)

In [3]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [4]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [5]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Train-Test Split

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### Building the ANN

In [7]:
### Initializing the ann
ann = tf.keras.models.Sequential()

In [8]:
### Adding the input and first hidden layer
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [9]:
### Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [10]:
### Adding the output layer
ann.add(tf.keras.layers.Dense(units = 1))

### Training the ANN

In [11]:
### Compiling the ann
ann.compile(optimizer= 'adam', loss = 'mean_squared_error')

In [12]:
### Training the model on the training set
ann.fit(X_train, y_train, epochs=100, batch_size= 32)

Epoch 1/100
240/240 [==============================] - 1s 3ms/step - loss: 651522.6250
Epoch 2/100
240/240 [==============================] - 1s 3ms/step - loss: 153405.5312
Epoch 3/100
240/240 [==============================] - 1s 2ms/step - loss: 22256.5078
Epoch 4/100
240/240 [==============================] - 1s 5ms/step - loss: 1010.9641
Epoch 5/100
240/240 [==============================] - 1s 4ms/step - loss: 347.9484
Epoch 6/100
240/240 [==============================] - 1s 4ms/step - loss: 342.5429
Epoch 7/100
240/240 [==============================] - 1s 4ms/step - loss: 340.2274
Epoch 8/100
240/240 [==============================] - 1s 4ms/step - loss: 337.7890
Epoch 9/100
240/240 [==============================] - 1s 4ms/step - loss: 334.7868
Epoch 10/100
240/240 [==============================] - 1s 4ms/step - loss: 331.3286
Epoch 11/100
240/240 [==============================] - 1s 3ms/step - loss: 327.6741
Epoch 12/100
240/240 [==============================] - 0s 2ms/st

240/240 [==============================] - 0s 1ms/step - loss: 27.6342
Epoch 98/100
240/240 [==============================] - 0s 1ms/step - loss: 26.1837
Epoch 99/100
240/240 [==============================] - 0s 1ms/step - loss: 26.9389
Epoch 100/100
240/240 [==============================] - 0s 1ms/step - loss: 26.5077


### Predicting the result on the test set

In [13]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test),1)),1))

[[430.74 431.23]
 [462.   460.01]
 [465.61 461.14]
 ...
 [472.61 473.26]
 [439.89 438.  ]
 [458.9  463.28]]
